<a href="https://colab.research.google.com/github/Sreelakshmi112/ds/blob/master/matrix_tran%26mul.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy
x = numpy.array([[1, 2], [4, 5]])

y = numpy.array([[7, 8], [9, 10]])

print ("The element wise multiplication of matrix is : ")

print (numpy.multiply(x,y))

print ("The product of matrices is : ")

print (numpy.dot(x,y))

print("Given matrix:")

print(x)

print ("The transpose of given matrix is : ")

print (x.T)

print ("The trace of given matrix is : ")

print (x.trace())

print(numpy.linalg.matrix_rank(x))

print(numpy.linalg.det(x))

print(numpy.linalg.inv(x))
print(numpy.linalg.eig(x))

The element wise multiplication of matrix is : 
[[ 7 16]
 [36 50]]
The product of matrices is : 
[[25 28]
 [73 82]]
Given matrix:
[[1 2]
 [4 5]]
The transpose of given matrix is : 
[[1 4]
 [2 5]]
The trace of given matrix is : 
6
2
-2.9999999999999996
[[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]
(array([-0.46410162,  6.46410162]), array([[-0.80689822, -0.34372377],
       [ 0.59069049, -0.9390708 ]]))
